HTML_intro/website/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from .models import User
from werkzeug.security import check_password_hash, generate_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user
from .models import User, Hotels

auth = Blueprint('auth', __name__)

@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    """
    Function that handles the signup page. It gets the details from the form and checks if they exist in the database
    If the email exists, the user is asked to enter another email as email field is unique. It also checks if the first
    and last name are strings and also if the passwords entered are the same.
    If the email doesn't exist, the user is added to the database and allowed to access the website's dashboard.
    """
    if request.method == 'POST':
        email = request.form.get('email')
        firstName = request.form.get('firstName')
        lastName = request.form.get('lastName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('User already exists', category='error')
        elif len(email) < 4:
            flash('Email must be a valid email', category='error')
        elif not isinstance(firstName, str):
            flash('Please enter a valid FirstName', category='error')
        elif not isinstance(lastName, str):
            flash('Please enter a valid LastName', category='error')
        elif password1 != password2:
            flash('Passwords do not match!', category='error')
        elif len(password1) < 7:
            flash('Password is too short', category='error')
        else:
            # add user to database
            new_user = User(email=email, firstName=firstName, lastName=lastName, password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            flash('Account created successfully!', category='success')
            login_user(new_user, remember=True)
            return redirect(url_for('views.dashboard', user=user))

    return render_template('Signup.html', user=current_user)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    """
    This function queries the database when the user enters their email and password. If the user exists in the database,
    they are logged in and if not, they are asked to signup or entera valid email/password
    """
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in Successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.dashboard'))
            elif not check_password_hash(user.password, password):
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email doesn\'t exist.', category='error')
    return render_template('Login.html', user=current_user)

@auth.route('/profile', methods=['GET', 'POST'])
@login_required # This decorator just ensures that the function can only be accessed if the user is logged in
def profile():
    """
    This function is responsible for allowing an existing user to alter the specific details of their profile
    including the email, first and last name.
    """
    user = User.query.all()
    if request.method == 'POST':
        current_user.email = request.form.get('email')
        current_user.firstName = request.form.get('firstName')
        current_user.lastName = request.form.get('lastName')

        try:
            db.session.commit()
            flash('Profile updated')
            return redirect('/dashboard')
        except:
            return "Update unsuccessful"
    else:
        return render_template('Profile.html', user=current_user)

@auth.route('/search', methods=['GET'])
@login_required
def search():
    """
    This function is responsible for filtering the results of hotels based on price and location when the user
    wished to see the hotels available in a certain location should they choose to search rather than scrolling
    through the entire website.
    """
    search_term_location = request.args.get('location')
    search_term_price = request.args.get('price')

    hotels_location = Hotels.query.filter_by(location=search_term_location).all()
    hotels_price = Hotels.query.filter_by(price=search_term_price).all()

    if hotels_location:
        flash('Location exists', category='success')
        return render_template('Search.html',hotels_location=hotels_location)
    elif hotels_price:
        flash('Hotels with that price are available', category='success')
        return render_template('Search.html', hotels_price=hotels_price)
    else:
        flash('No facilities in that area/price range', category='error')
        return redirect(url_for('views.dashboard'))

    return render_template('Search.html')

@auth.route('/logout')
@login_required
def logout():
    # This function is responsible for logging out a user and redirecting them ot the login page.
    logout_user()
    return redirect(url_for('auth.login'))

HTML_intro/website/views.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user
from .models import Hotels

views = Blueprint('views', __name__)

@views.route('/')
def home():
    # This function redirects to the Home page
    return render_template("Home.html")

@views.route('/dashboard')
@login_required
def dashboard():
    # This function rdirects the user to the dashboard and it requires a user to have an account created.
    # The hotels variable holds all the details of the hotels present in the database and so we have to
    # pass the details to the template so that we can dynamically display the details of the hotels to
    # the user.
    hotels = Hotels.query.all()
    return render_template('Dashboard.html', hotels=hotels)

@views.route('/deals')
def deals():
    # This function redirects the user to the deals page that contains the offers available at various hotels.
    hotels = Hotels.query.all()
    return render_template('Pricing.html', hotels=hotels)

HTML_intro/website/templates/Base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Base Page{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
        <link rel="icon" type="image/png" href="{{ url_for('static', filename='favicon.png') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
        <script src="{{ url_for('static', filename='script.js') }}"></script>
    </head>
    <body>
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('views.dashboard') }}">DashBoard</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
              </li>
              <li class="nav-item">
                <div class="container text-center">
                  <form class="row gx-3 gy-2 align-items-center justify-content-end custom form" method="get" action="{{ url_for('auth.search') }}">
                    <div class="col-sm-4">
                      <label class="visually-hidden" for="location">Name</label>
                      <input type="text" name="location" class="form-control" id="location" placeholder="Search by Location">
                    </div>
                    <div class="col-sm-4">
                      <label class="visually-hidden" for="price">Price</label>
                      <input type="number" name="price" class="form-control" id="price" placeholder="Filter by Price">
                    </div>
                    <div class="col-sm-2">
                      <button type="submit" class="btn btn-primary">Search</button>
                    </div>
                  </form>
                </div>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{ url_for('views.home') }}">About us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('views.deals') }}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.signup') }}">Sign Up</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>

      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      {% for category, message in messages %}
      {% if category == 'error' %}
      <div class="alert alert-danger alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-bs-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% else %}
      <div class="alert alert-success alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-bs-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endif  %}
      {% endfor %}
      {% endif %}
      {% endwith %}

      {% block content %}{% endblock %}
    </body>
  </div>
  <div class="card text-center">
    <div class="card-footer text-muted">
      <p>For more information, look up the development team at:</p>
      <a href="https://github.com/malvinmuthuuri47" target="_blank">Malvin</a>
      <a href="https://github.com/generalblaze" target="_blank">Benjamin</a>
      <a href="https://github.com/ifedolapoomoniyi" target="_blank">Ifedolapo</a>
    </div>
</html>

HTML_intro/website/templates/Dashboard.html
{% extends 'Base.html' %}

{% block title %} Name of Hotel {% endblock %}

{% block content %}

<div class="dashboard">

    <!-- Sidebar -->
    
    <section class="sidebar">
        <a href="{{ url_for('views.dashboard') }}">Hotels in your area</a>
        <a href="" onclick="alert('Feature coming soon')">Deals for you</a>
        <a href="{{ url_for('auth.profile') }}">Profile details </a>
    </section>


    <!-- Hotel details -->

    {% for hotel in hotels %}
    <section class="hotel-details-container">
        <h3 class="hotel-name">{{ hotel.name }} Hotel</h3>
        <div class="hotel-location">
            <img src="../static/location.png" alt="">
            <span>{{ hotel.location }}</span>
        </div>
        <div class="images-container">
            <img src="{{ url_for('static', filename='images/' + hotel.image) }}" alt="Db image">
            <img src="{{ url_for('static', filename='images/' + hotel.image) }}" alt="Db image">
            <img src="{{ url_for('static', filename='images/' + hotel.image) }}" alt="Db image">
            <img src="{{ url_for('static', filename='images/' + hotel.image) }}" alt="Db image">
        </div>

        <div class="hotel-details-flexer">
            <div class="hotel-details">
                <h4>Details of {{ hotel.name }} Hotel:</h4>
                <div class="hotel-features">
                    <div class="hotel-feature">
                        Number of Rooms: {{ hotel.rooms }}
                    </div>
                    <div class="hotel-feature">
                        Price per Night: {{ hotel.price }}$
                    </div>
                    <div class="hotel-feature">
                        {% set data = hotel.services %}
                        {% for word in data.split(",") %}
                            {% if loop.first %}
                                {{ word.strip() }}
                            {% else %}
                                <br>{{ word.strip() }}
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
        
                <div class="hotel-desc">
                    <h6>Description</h6>
                    {% set text = hotel.description %}
                    {% set modified_text = text|replace('.', '.<br><br>') %}

                    {{ modified_text|safe }}
                </div>
    
            </div>

            <div class="booking">
                <h4>Book rooms in {{ hotel.name }} Hotels online</h4>
                <div class="booking-details">
                    <form action="" class="booking-form">
                        
                        <label for="book-date">Date</label>
                        <input type="date" id="book-date">

                        <label for="no-of-adults">Adults</label>
                        <input type="number" id="no-of-adults" placeholder="1" required>

                        <label for="rooms">No of rooms</label>
                        <input type="number" required placeholder="1">

                        <p>Enter your phone number to start the booking process</p>
                        <input type="number" name="phone-number" id="phone-number" placeholder="+234 801 234 5678" required>
                        
                        <button type="submit" class="book-btn" onclick="showAlert()">Book Now</button>
                    </form>
                </div>
            </div>
        </div>
    
    </section>
    

</div>
{% endfor %}


{% endblock %}

HTML_intro/website/templates/Home.html
{% extends 'Base.html' %}

{% block title %} Home page {% endblock %}

{% block content %}

<div class="landing">
    <h1>OurName.ng</h1>
    <h4>Find and book hotels anywhere in Nigeria, all without leaving your favorite couch</h4>
    <!-- <form action="" class="search">
        <img src="../static/search.png" alt="" class="search-icon">
        <input type="text" name="" class="search-text" placeholder="find a hotel">
        <button class="search-btn">Find Hotels</button>
    </form> -->
</div>


<!-- Services section -->

<section class="home-services">
    <h2>Our Services</h2>
    <div class="services-cards">
        <div class="services-card">Easy Booking</div>
        <div class="services-card">Support Team</div>
        <div class="services-card">Zero Stress</div>
        <div class="services-card">Competitive Pricing</div>
        <div class="services-card">24/7 Availability</div>
    </div>
</section>


<!-- About Section -->

<section class="about-section">
    <h4>About Hotels.ng</h4>
    <p>
        Our team at Hotels.ng saw the problems of neglect and lack of attention the tourist section of Nigeria faced. And as students of <a href="">Alx SE Africa</a>, we knew we had the technical know-how to help improve the online experience of prospective tourists. Hence, <b>Hotels.ng</b> was born
    </p>
    <p>
        Hotels.ng was inspired from a desire to bridge the gap between Hotels and their guests, a need to help tourists find a place to rest in an unfamiliar country.
    </p>
</section>



<!-- Our team -->

<section class="team-section">
    <h3>Our Team</h3>
    <div class="team-member-container">
        
        <div class="team-member">
            <div class="member-desc">
                <img src="../static/Malvin.jpg" alt="">
                <div class="member-name">Malvin Muthuuri</div>
            </div>
            <div class="team-socials">
                <a href="https://github.com/malvinmuthuuri47" class="github">
                    <img src="../static/github.png" alt="">
                </a>
                <a href="https://twitter.com/Malvin2572" class="twitter">
                    <img src="../static/twitter.png" alt="">
                </a>
                <a href="https://www.linkedin.com/in/malvin-m-005a8a253" class="linkedin">
                    <img src="../static/linkedin.png" alt="">
                </a>
            </div>
        </div>

        <div class="team-member">
            <div class="member-desc">
                <img src="../static/Ifedolapo.jpg" alt="">
                <div class="member-name">Ifedolapo Omoniyi</div>
            </div>
            <div class="team-socials">
                <a href="https://github.com/ifedolapoomoniyi" class="github">
                    <img src="../static/github.png" alt="">
                </a>
                <a href="https://twitter.com/ife_ifedolapo" class="twitter">
                    <img src="../static/twitter.png" alt="">
                </a>
                <a href="https://www.linkedin.com/in/ifedolapo-omoniyi/" class="linkedin">
                    <img src="../static/linkedin.png" alt="">
                </a>
            </div>
        </div>
        
        <div class="team-member">
            <div class="member-desc">
                <img src="../static/Benjamin.JPG" alt="">
                <div class="member-name">Benjamin Princewill</div>
            </div>
            <div class="team-socials">
                <a href="https://github.com/generalblaze" class="github">
                    <img src="../static/github.png" alt="">
                </a>
                <a href="https://twitter.com/benii_silva" class="twitter">
                    <img src="../static/twitter.png" alt="">
                </a>
                <a href="https://www.linkedin.com/in/fafaa-princewill-4632bb271/" class="linkedin">
                    <img src="../static/linkedin.png" alt="">
                </a>
            </div>
        </div>

    </div>

</section>



<!-- github link -->

<div class="github-link">
    Project code, an extensive description and challenges are all contained <a href="https://github.com/malvinmuthuuri47/portfolio_project/tree/main">here</a>
</div>



<!-- deals -->

<section class="special-deals">
    <h3>Special Hotel Deals and Offers</h3>
    <div>Enter your email address to recieve extra-special hotel deals</div>
    <div class="subscribe">
        <form action="">
            <input type="email" name="Email" class="email-text" placeholder="Enter your email address">
            <button type="submit" class="subscribe-btn" onclick="showAlert()">Subscribe</button>
        </form>
    </div>
</section>


{% endblock %}

HTML_intro/website/templates/Login.html
{% extends 'Base.html' %}

{% block title %} Login Page {% endblock %}

{% block content %}
<p>
    Login here
</p>
<div class="container">
    <form method="post">
        <div class="form-group">
          <label for="email">Email address</label>
          <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" placeholder="Enter email">
          <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input type="password" class="form-control" id="password" name="password" placeholder="Password">
        </div>
        <br/>
        <button type="submit" class="btn btn-primary">Login</button> <br/>
        <a href="{{ url_for('auth.signup') }}">Don't have an account? Click here to Signup</a>
    </form>
</div>
{% endblock %}

HTML_intro/website/templates/Pricing.html
{% extends 'Base.html' %}

{% block title %} Hot Deals {% endblock %}

{% block content %}

<h2 class="big-header">Hotels.ng</h2>

<form action="" class="search">
    <img src="../static/search.png" alt="" class="search-icon">
    <input type="text" name="" class="search-text" placeholder="Find a hotel">
    <button class="search-btn">Find Hotels</button>
</form>


<!-- Top Deals -->

<section class="top-deals-container">
    <h3>This Week's Top Deals</h3>
    <p>A selection of the best deals, only available this week</p>
   

    <!-- I temporarily hardcoded it because we werent generating the names of each hotels and their pricing -->

    <!-- <div class="top-deals">
        {% for hotel in hotels %}
        <a href="{{ url_for('views.dashboard') }}" class="top-deal">
            <img src="{{ url_for('static', filename='images/' + hotel.image) }}" alt="Db image">
        </a>
        {% endfor %}
        
    </div> -->


    <div class="top-deals">
        <a href="{{ url_for('views.dashboard') }}" class="top-deal">
            <img src="../static/images/Hilton.webp" alt="">
            <div class="percentage-off">Up to 25% off</div>
            <div class="top-deal-name">Transcorp Hilton, Abuja</div>
            <div class="location"><img src="../static/location.png" alt=""> Abuja</div>
        </a>
        <a href="{{ url_for('views.dashboard') }}" class="top-deal">
            <img src="../static/images/Eko-Hotel.webp" alt="">
            <div class="percentage-off">Up to 19% off</div>
            <div class="top-deal-name">Eko Hotel and Suites</div>
            <div class="location"><img src="../static/location.png" alt=""> Victoria Island, Lagos</div>
        </a>
        <a href="{{ url_for('views.dashboard') }}" class="top-deal">
            <img src="../static/images/Federal-palace.webp" alt="">
            <div class="percentage-off">Up to 10% off</div>
            <div class="top-deal-name">The Federal Palace Hotel</div>
            <div class="location"><img src="../static/location.png" alt=""> Ahmadu Bello Street, Victoria Island</div>
        </a>
        <a href="{{ url_for('views.dashboard') }}" class="top-deal">
            <img src="../static/images/Oriental.webp" alt="">
            <div class="percentage-off">Up to 19% off</div>
            <div class="top-deal-name">Lagos Oriental Hotel</div>
            <div class="location"><img src="../static/location.png" alt=""> Victoria Island, Lagos</div>
        </a>
        <a href="{{ url_for('views.dashboard') }}" class="top-deal">
            <img src="../static/images/Sheraton.webp" alt="">
            <div class="percentage-off">Up to 19% off</div>
            <div class="top-deal-name">Sheraton Hotel</div>
            <div class="location"><img src="../static/location.png" alt=""> Ikeja, Lagos State</div>
        </a>


</section>


<!-- popular locations -->

<section>
    <h3 class="popular-hotel-header">Popular Hotels to visit in Nigeria</h3>
    <div class="popular-hotel-container">
        <div class="popular-hotel">
            <img src="../static/images/Hilton.webp" alt="">
            <div>Transcorp Hilton, Abuja</div>
        </div>
        <div class="popular-hotel">
            <img src="../static/images/WheatBaker.webp" alt="">
            <div>The WheatBaker Hotel, Lagos</div>
        </div>
        <div class="popular-hotel">
            <img src="../static/images/Eko-Hotel.webp" alt="">
            <div>Eko Hotel and Suites</div>
        </div>
        <div class="popular-hotel">
            <img src="../static/images/Oriental.webp" alt="">
            <div>Lagos Oriental Hotel</div>
        </div>
        <div class="popular-hotel">
            <img src="../static/images/Sheraton.webp" alt="">
            <div>Sheraton Hotels</div>
        </div>
        <div class="popular-hotel">
            <img src="../static/images/Federal-palace.webp" alt="">
            <div>Federal Palace Hotel and Casino</div>
        </div>
    </div>
</section>





<!-- <p>
    Welcome. In this page, you will find the specific details of each and every facility we have along with the prices and services offered at each facility.
</p>
<p>
    We can implement pricing in this page and segment each hotel providing specific details about each facility we might include in this page.
</p>
<h3>
    We can show users the prices of various bookings without them having to login here but to book, they will be required to login/signup.
    It will be similar to the dashboard only that in the dashboard page, the user will be able to book a hotel so let's advertise the amenities in this page.
</h3> -->
{% endblock %}

HTML_intro/website/templates/Profile.html
{% extends 'Base.html' %}

{% block title %} Profile {% endblock %}

{% block content %}

<div class="profile-dashboard">

    <!-- Sidebar -->
    
    <section class="profile-sidebar">
        <a href="{{ url_for('views.dashboard') }}">Hotels in your area</a>
        <a href="" onclick="alert('Feature coming soon')">Deals for you</a>
        <a href="{{ url_for('auth.profile') }}">Profile details </a>
    </section>




    <div class="profile-main">

        <h4>Edit your profile details</h4>

        <form action="{{ url_for('auth.profile') }}" method="POST">
            <label for="email">Email</label>
            <input type="email" name="email" id="email" value = "{{ user.email }}" required>
       
            <label for="firstName">First Name</label>
            <input type="text" id="firstName" name="firstName" value="{{ user.firstName }}" required>
    
            <label for="lastName">Last Name</label>
            <input type="text" name="lastName" id="lastName" value="{{ user.lastName }}" required>
    
            <input type="submit" value="Update Profile" id="profile-submit">
        </form>
        
        <a href="{{ url_for('views.dashboard') }}" class="btn btn-primary mt-4 mb-4">Back to Dashboard</a>
    </div>
    </div>





{% endblock %}

HTML_intro/website/templates/Search.html
{% extends 'Base.html' %}

{% block title %} Hotels in Your Area {% endblock %}

{% block content %}
    <h2>Search Results:</h2>
    {% if hotels_location %}
        <ul>
            {% for hotel in hotels_location %}
                <p><img src="{{ url_for('static', filename='images/' + hotel.image) }}" alt="Hotel image" class="search-img"></p>
                <h4> {{ hotel.name }} </h4>
                <div><img src="../static/location.png" alt="">{{ hotel.address }}, {{ hotel.location }}</div>
                <p>Price: {{ hotel.price }} $</p>
                <p>Services: {{ hotel.services }}</p>
                <p></p>
            {% endfor %}
        </ul>
    {% elif hotels_price %}
        <ul>
            {% for hotel in hotels_price %}
            <p><img src="{{ url_for('static', filename='images/' + hotel.image) }}" alt="Hotel image" class="search-img"></p>
            <h4> {{ hotel.name }} </h4>
            <div><img src="../static/location.png" alt="">{{ hotel.address }}, {{ hotel.location }}</div>
            <p>Price: {{ hotel.price }} $</p>
            <p>Services: {{ hotel.services }}</p>
        {% endfor %}
        </ul>
    {% else %}
        <p>No hotels found within that area</p>
    {% endif %}

    <br />
    <a href="{{ url_for('views.dashboard') }}" class="btn btn-primary">Back to Dashboard</a>
{% endblock %}

HTML_intro/website/templates/Signup.html
{% extends 'Base.html' %}

{% block title %} Sign Up Page {% endblock %}

{% block content %}
<p>
    Sign up here
</p>
<!--
    Please i implore you in the name of Jesus Christ. You can change the UI aspect of this page but do not in any way modify the id and name values in this form as doing so with cause errors with our database.

    Also note the url_for() function. Do not in any way change the values put inside as this function generates an absolute path to the files that Flask needs to run this app.

 -->
<div class="container">
    <form method="post">
        <div class="form-group">
          <label for="email">Email address</label>
          <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" placeholder="Enter email">
          <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
          <label for="firstName">First Name</label>
          <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Example: John">
        </div>
        <div class="form-group">
            <label for="lastName">Last Name</label>
            <input type="text" class="form-control" id="lastName" name="lastName" placeholder="Example: Doe">
        </div>
        <div class="form-group">
            <label for="password1">Password</label>
            <input type="password" class="form-control" id="password1" name="password1" placeholder="Password">
        </div>
        <div class="form-group">
            <label for="password2">Password</label>
            <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm Password">
        </div>
        <br/>
        <button type="submit" class="btn btn-primary">Submit</button><br/>
        <a href="{{ url_for('auth.login') }}">Already have an account? Click here to Login</a>
    </form>
</div>

{% endblock %}